reporter {
  reports {
    customTemplate {
      pluginId = "PdfTemplate"
      description = "Custom template report."
    }
    webApp {
      pluginId = "WebApp"
      description = "Custom web app report."
    }
  }
}
